# Generated by Django 3.2.24 on 2026-04-28 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='事件标题')),
                ('description', models.TextField(blank=True, verbose_name='事件描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地点')),
                ('max_attendees', models.PositiveIntegerField(default=0, verbose_name='最大参与人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '事件',
                'verbose_name_plural': '事件列表',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='参与者姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮件')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话号码')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.event', verbose_name='关联事件')),
            ],
            options={
                'verbose_name': '参与者',
                'verbose_name_plural': '参与者列表',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='events_even_start_d_d4b514_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'start_date'], name='events_even_categor_ed450e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('event', 'email')},
        ),
    ]
